# Generated by Django 4.0.6 on 2022-08-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField(unique=True, verbose_name='Номер заказа')),
                ('price_dol', models.IntegerField(verbose_name='Стоимость, $')),
                ('date', models.DateField(verbose_name='Дата заказа')),
                ('price_rub', models.IntegerField(verbose_name='Стоимость, руб')),
            ],
        ),
    ]
